Quoting and whitespace.

diff --git a/bin/chroot-mount b/bin/chroot-mount
--- a/bin/chroot-mount
+++ b/bin/chroot-mount
@@ -7,7 +7,7 @@
 #
 # chroot-manager is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 2 or 3 of the License at your 
+# the Free Software Foundation, version 2 or 3 of the License at your
 # option.
 #
 # chroot-manager is distributed in the hope that it will be useful,
@@ -20,13 +20,13 @@
 
 
 CHROOT_MANAGER_HOME=$(dirname ${0})/..
-CHROOT_MANAGER_LIBEXEC="${CHROOT_MANAGER_HOME}/libexec/chroot-manager"
-source "${CHROOT_MANAGER_LIBEXEC}/chroot-functions.bash" || die "Couldn't source chroot-functions.bash."
+CHROOT_MANAGER_LIBEXEC="${CHROOT_MANAGER_HOME}"/libexec/chroot-manager
+source "${CHROOT_MANAGER_LIBEXEC}"/chroot-functions.bash || die "Couldn't source chroot-functions.bash."
 
 TARGET_CHROOT="${1}"
 if [[ -z ${TARGET_CHROOT} ]]; then
-	eerror "Expected one argument (the name of the chroot)"
-	exit 1
+    eerror "Expected one argument (the name of the chroot)"
+    exit 1
 fi
 
 init_chroot_env ${TARGET_CHROOT}
diff --git a/bin/chroot-shell b/bin/chroot-shell
--- a/bin/chroot-shell
+++ b/bin/chroot-shell
@@ -20,8 +20,8 @@
 
 
 CHROOT_MANAGER_HOME=$(dirname ${0})/..
-CHROOT_MANAGER_LIBEXEC="${CHROOT_MANAGER_HOME}/libexec/chroot-manager"
-source "${CHROOT_MANAGER_LIBEXEC}/chroot-functions.bash" || die "Couldn't source chroot-functions.bash."
+CHROOT_MANAGER_LIBEXEC="${CHROOT_MANAGER_HOME}"/libexec/chroot-manager
+source "${CHROOT_MANAGER_LIBEXEC}"/chroot-functions.bash || die "Couldn't source chroot-functions.bash."
 
 TARGET_CHROOT="${1}"
 if [[ -z ${TARGET_CHROOT} ]]; then
